### ISSUE TITLE
Send by word

### ISSUE THREAD

**Issue by MichaelWengren** [gudatr/godot-ai-rpg#1]
Is there is a way to get answer from server word by word? This will be much faster than waiting for the server to complete the entire sentence and then send it back to Godot.

**Comment by gudrob** [comment]
stream: true needs to be set in the body and then you would have to find a way to fetch a partial response from the http client. If you find a way to do this, a PR would be appreciated.
All other parameters are described here: https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md

**Comment by MichaelWengren** [comment]
I'm desperately trying to understand why it is so slow in Godot. 
Server actually works very quickly, you can check this by running it separately and going to the 127.0.0.1:8080 in the browser, is it possible to somehow achieve a similar speed in Godot?

And is it possible to implement this example using GDScript only?

**Comment by gudrob** [comment]
The browser chat uses stream as far as I know. Have you tried getting that to work in Godot?
Or are you talking about sending requests to the API?
If so, what is the request you are sending?
And just out of curiosity, what model are you currently using?

**Comment by MichaelWengren** [comment]
> Have you tried getting that to work in Godot?

No

> And just out of curiosity, what model are you currently using?

openchat_3.5.Q5_K_M produces pretty good results compared to most models of similar size

**Comment by MichaelWengren** [comment]
I have doubts if this server-client approach makes any sense at all, llama can be compiled through gdextension and have a native implementation, this will certainly give the fastest results, but I have concerns that it may block the main thread and the engine will freeze a lot. Here is a similar native implementation of whisper.cpp project: https://github.com/V-Sekai/godot-whisper and in a real test it's literally unusable.

This forced me to look for alternative solutions, in addition to the server-client approach, there is another option. Godot has an OS class and through _create_process_ can create a new process by launching any application, in our case it can be _main_ from llama.cpp and you can pass arguments directly from gdscript/c# via _OS.execute_ and get a response.

**Comment by gudrob** [comment]
I have explored those approaches actually. Running the main app does not allow parallel context and processing or at least I could not figure out a way to do it properly. And that is something you would need for something that is similar to a dungeon master.

I am a bit confused why you would mention the create_process thing. The app already creates a sub process? Why use the godot api? Does that bring any Advantage?

Also restarting the main exe for every prompt is absolutely not feasible and consumes immense amounts of resources as it would load the model every time. Or is there a way to use the main and not reload the model?

So summarised the problems I tried to solve using client-server:
- Parallelization of Processing on the AI's side
- Multiple Tasks in Godot that can be awaited without much hassle
- Multiple Contexts and Sessions
- Model Weight Resuage

I think the central problem you are facing is still the stream parameter which is missing in my implementation. But the overhead from this constellation is neglible. Especially if you look at the downsides of directly querying the model using the main application (which I have not been able to overcome). Have you tried benchmarking anything?

**Comment by MichaelWengren** [comment]
> Does that bring any Advantage?

Theoretically can be faster to read directly from console avoiding network, but since server uses loopback address it's quite fast.

> Or is there a way to use the main and not reload the model?

Main has interactive mode (-i) and this way model is kept in memory while you chat. But there is no way to reset system prompt without unloading model from memory, in server this is possible.

> Have you tried benchmarking anything?

Yes, I compiled this under Linux https://github.com/opyate/godot-llm-experiment and it's just insanely slow, using llama with gdextension is not a good option unless some C++ wizzard do some magic with threads there. On Windows I can't compile this because of errors in scons file.

So far your implementation is the best one. Setting stream to true does work in Godot console (and quite fast) but there is obviously errors in game because it can't parse that properly.
Server readme says that in stream mode only _content_ and _stop_ will be returned until end of completion, that _stop_ is just a boolean so this should help with parsing, have you tried anything with that?

**Comment by KoxaKoxama** [comment]
I also noticed a significant slowdown due to the fact that the text comes in whole pieces.
Does this have a solution?

**Comment by gudrob** [comment]
Like I said to Michael, technically, yes. With the stream parameter set to true in the request. But then you will have to load multiple responses from the server with the httpClient. If you can get to work, that would be great, just pass a PR.

Also fiddling with the start up arguments of the server might help. Maybe more VRAM or threads could help. I just applied a config that should work on lower end devices.

**Comment by gudrob** [comment]
Fixed by https://github.com/gudatr/godot-ai-rpg/commit/34484bcbaf55fa650b73f117c5633b4635e03d82
